
version: 2

models:
  - name: managers_cleaned
    description: "cleans managers dates"
    tests:
      - dbt_expectations.expect_table_column_count_to_equal:
          value: 4
  - name: players_cleaned
    tests:
      - dbt_expectations.expect_table_column_count_to_equal:
          value: 3
    description: "cleans player dates"
  - name: players_and_incumbent_manager
    description: "combines players & managers to show the manager at the time a player joined"
    
sources:
  - name: dev
    database: learning  
    schema: dev  
    tables:
    - name: players
    - name: managers

exposures:
  - name: tableau_dashboard
    type: dashboard
    owner:
      name: Dan
    depends_on:
      - ref('players_and_incumbent_manager')
    description: Shows the number of managers that helped build the current squad
    url: https://public.tableau.com/app/profile/danjpharrington/viz/number_of_players_per_manager/Squads
    maturity: high
